### ISSUE TITLE
TODOs from Jesse/James Sync 9/23 2pm

### ISSUE THREAD

**Issue by JesseDoesHCI** [uwcse440/web-cse440-24au#27]
- [x] Make A0 non-submission in Canvas
- [x] Make shared slide decks for A0: one for each section
- [x] Write Milestone 1 Report Website Text
- [ ] Create Rubric for Milestone 1 Report
- [x] Change 1.1 to pure completion grading

**Comment by jayfo** [comment]
Moved the rubric out to #41.
