### ISSUE TITLE
Confirm Site Builds Correctly

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-24au#3]
Building the site involves a lot of versions and dependencies. 

Let's confirm everybody can build per `README.md`, successfully executing a `yarn export`.

- [x] Confirm Jesse can build.
- [x] Confirm Katelyn can build.
- [x] Confirm at least one person can build on a Mac.

**Comment by Mooniem** [comment]
Confirmed! I can build it on a Mac
