### ISSUE TITLE
Canvas: Milestone 1 Templates Cleanup

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-24au#33]
- Confirm `- ROOT -` can now be deleted.
- This will also allow deletion of `Still Need Revision`.

If it cannot be deleted, let's instead create a top-level `Archive` or equivalent. It could be a temporary holding place for things we do not yet want to delete, but which we also are no longer using.

**Comment by JesseDoesHCI** [comment]
made top level `Archived` folder, deleted `Still Need Revision`
