### ISSUE TITLE
Clarify Removal of Instruction and Template Slides / Marking

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-24au#35]
In the "Using this Template" slide, adjust:

> We recommend removing all instruction and template slides from your deck before submission.

to

> Remove instruction slides and template markings from your deck before submission.

This should be done in the existing approved template, and in new templates going forward.

**Comment by jayfo** [comment]
This will match text I'm putting in the assignments too.

**Comment by JesseDoesHCI** [comment]
Text updated for Milestone 1 templates, noted for future templates.
