### ISSUE TITLE
Canvas Rubrics for A1.2, A1.3, A1.4

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-24au#36]
- [x] A1.2 and A1.3 currently have their ⭐ in opposite directions.  I think A1.2 is preferred.
- [ ] A1.4 needs a ⭐ rubric matching the website.
- [ ] A1.4 then needs published.

**Comment by jayfo** [comment]
@JesseDoesHCI : I added the checkboxes to this issue just now.

Do the permission you have allow you to check those off, or to otherwise edit my comment?

I think these are now all complete, but the issue hadn't been closed, so I was needlessly re-checking on it.  So I'm wondering if these will help us both known that things are done and the issue is closed.

**Comment by JesseDoesHCI** [comment]
> * [x]  A1.2 and A1.3 currently have their ⭐ in opposite directions.  I think A1.2 is preferred.
> * [x]  A1.4 needs a ⭐ rubric matching the website.
> * [x]  A1.4 then needs published.


I can't toggle your checkboxes, which is a perplexing design choice. 

I can quote reply and edit them there– maybe that's our MO?

(Regardless, sorry for forgetting to close this when I completed! leaving it open so we can resolve this discussion tho)

**Comment by jayfo** [comment]
Ok let's discuss sometime soon.  Permissions don't seem to allow me to give you this ability without also giving the ability to push/merge.  Not inherently a problem, and perhaps just highlights that I'm mis-using Github issues.  But would be good to understand how to think about this.
