### ISSUE TITLE
Determine and Post Office Hours

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-24au#4]
I'd like you each to set an office hour. 

In the past, it's worked well to have one of these on Wednesday, one on Thursday.

- Coordinate on times.
- Book rooms in which to hold that office hour.  Jesse can help Katelyn with this in CSE.
- Let me know and I'll update website.

**Comment by JesseDoesHCI** [comment]
Timing decided, rooms booked:

- Katelyn: Wed 3-4, CSE2/Gates 152
- Jesse: Thurs 12-1, CSE2/Gates 152

still need to update website with this info

**Comment by jayfo** [comment]
Fixed in #14.
