### ISSUE TITLE
Polish and Publish A3.1

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-24au#73]
Template:
- Copy-paste bug in the header of the task analysis slide.
- Because everybody will answer the same 11 questions, let's put those in the template itself.
- Then publish it to the groups.

Canvas:
- Create the submission.

Web:
- Add the Canvas link to the submission, disable the under development banner.

**Comment by JesseDoesHCI** [comment]
all steps done, waiting on merge: https://github.com/uwcse440/web-cse440-24au/pull/74
