### ISSUE TITLE
Draft Google form for Section Swap

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-24au#8]
- This will be emailed on Monday.
- With explanation that groups must be formed within section.
- A reminder made in class on Thursday.
- Due Thursday 1pm.
- An email will follow with approved swaps.

**Comment by JesseDoesHCI** [comment]
Editable Version: in [Student-Facing Docs folder](https://drive.google.com/drive/folders/1Sm12CpuMNsKBqk6E_Ri875hfFs0A-IRS?usp=drive_link)

Public-Facing Link: https://forms.gle/qnpkAP4qs3RHHEJp6
