### ISSUE TITLE
Finish Assignment 4.2

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-24au#97]
- The Canvas assignment needs created.
- It is an individual assignment.

- It then needs linked in the spec.
- And the UnderDevelopment flag needs cleared for that page.

- It needs distributed in Drive.  I did groups A and B to show how I intend it.

**Comment by JesseDoesHCI** [comment]
- [x] assignment created
- [x] individual
- [x] linked in spec
- [x] flag removed
- [x] template distributed
